{% set version = "2.3.0" %}

package:
  name: openalea.container
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 1
  script: python setup.py install --prefix=$PREFIX

requirements:
  build:
    - openalea.deploy
  run:
    - python
    - openalea.deploy
    - numpy

test:
  imports:
    - openalea.container
  requires:
    - nose
  source_files:
    - test/
    - test/*.py

  commands:
    - nosetests -v

about:
  home: http://github.com/openalea/container
  license: Cecill-c License
  summary: Container is a set of data structures used in openalea such as graph, grid, topomesh.

