from openalea.core import CompositeNodeFactory as CNF

__name__ = 'openalea.container.example'

__editable__ = True
__description__ = ''
__license__ = ''
__url__ = ''
__alias__ = []
__version__ = ''
__authors__ = 'Jerome Chopard'
__institutes__ = ''
__icon__ = ''

__all__ = ['_140583807927568']

_140583807927568 = CNF(name='simple_add',
                       description='',
                       category='Unclassified',
                       doc='',
                       inputs=[],
                       outputs=[],
                       elt_factory={2: ('openalea.data structure', 'int'),
                                    3: ('openalea.data structure', 'int'),
                                    4: ('openalea.numpy.math', 'add')},
                       elt_connections={39330296: (2, 0, 4, 0),
                                        39330320: (3, 0, 4, 1)},
                       elt_data={2: {'block': False,
                                     'caption': '7',
                                     'delay': 0,
                                     'hide': True,
                                     'id': 2,
                                     'lazy': True,
                                     'port_hide_changed': set([]),
                                     'posx': 3.073419640894489,
                                     'posy': 1.2293678563578005,
                                     'priority': 0,
                                     'use_user_color': False,
                                     'user_application': None,
                                     'user_color': None},
                                 3: {'block': False,
                                     'caption': '5',
                                     'delay': 0,
                                     'hide': True,
                                     'id': 3,
                                     'lazy': True,
                                     'port_hide_changed': set([]),
                                     'posx': 39.109131453968075,
                                     'posy': 0.7178471190306084,
                                     'priority': 0,
                                     'use_user_color': False,
                                     'user_application': None,
                                     'user_color': None},
                                 4: {'block': False,
                                     'caption': 'add',
                                     'delay': 0,
                                     'hide': True,
                                     'id': 4,
                                     'lazy': True,
                                     'port_hide_changed': set([]),
                                     'posx': 15.367098204472441,
                                     'posy': 44.871926757059526,
                                     'priority': 0,
                                     'use_user_color': False,
                                     'user_application': None,
                                     'user_color': None},
                                 '__in__': {'block': False,
                                            'caption': 'In',
                                            'delay': 0,
                                            'hide': True,
                                            'id': 0,
                                            'lazy': True,
                                            'port_hide_changed': set([]),
                                            'posx': 0,
                                            'posy': 0,
                                            'priority': 0,
                                            'use_user_color': True,
                                            'user_application': None,
                                            'user_color': None},
                                 '__out__': {'block': False,
                                             'caption': 'Out',
                                             'delay': 0,
                                             'hide': True,
                                             'id': 1,
                                             'lazy': True,
                                             'port_hide_changed': set([]),
                                             'posx': 0,
                                             'posy': 0,
                                             'priority': 0,
                                             'use_user_color': True,
                                             'user_application': None,
                                             'user_color': None}},
                       elt_value={2: [(0, '7')], 3: [(0, '5')], 4: [],
                                  '__in__': [], '__out__': []},
                       elt_ad_hoc={2: {
                           'position': [3.073419640894489, 1.2293678563578005],
                           'useUserColor': False,
                           'userColor': None},
                                   3: {'position': [39.109131453968075,
                                                    0.7178471190306084],
                                       'useUserColor': False,
                                       'userColor': None},
                                   4: {'position': [15.367098204472441,
                                                    44.871926757059526],
                                       'useUserColor': False,
                                       'userColor': None},
                                   '__in__': {'position': [0, 0],
                                              'useUserColor': True,
                                              'userColor': None},
                                   '__out__': {'position': [0, 0],
                                               'useUserColor': True,
                                               'userColor': None}},
                       lazy=True,
                       eval_algo='LambdaEvaluation',
                       )
